version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delitutti_erp
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: delitutti_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: B05>04j1oOWA
      MYSQL_DATABASE: delitutti_sistema
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: bpSo4Q731iVz
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
